# Generated by Django 3.1.3 on 2021-01-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Patronymic')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Patronymic')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suddop.client')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('passportSeries', models.IntegerField(max_length=4, verbose_name='Passport series')),
                ('passportNumber', models.IntegerField(max_length=6, verbose_name='Passport number')),
            ],
            bases=('suddop.client',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suddop.client')),
                ('sex', models.CharField(max_length=15, verbose_name='Sex')),
                ('dateOfBirth', models.DateField(verbose_name='Birth day')),
                ('document', models.CharField(max_length=25, verbose_name='Document')),
                ('snils', models.IntegerField(max_length=15, verbose_name='SNILS')),
            ],
            bases=('suddop.client',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.CharField(max_length=20, verbose_name='For age:')),
                ('description', models.TextField(max_length=500, verbose_name='Program description')),
                ('dateOfStart', models.DateField(verbose_name='Date of beginning')),
                ('dateOfEnd', models.DateField(verbose_name='Date of ending')),
                ('learningLevel', models.CharField(max_length=25, verbose_name='Learning level')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.student')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfConclusion', models.DateField(verbose_name='Date of conclusion')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.program')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.applicant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.student')),
            ],
        ),
    ]
